name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: fmt
      run: cargo fmt -- --check --color always
    - name: clippy
      run: cargo clippy --no-deps
    - name: build
      run: cargo build
    # - name: test
    #   run: cargo test
