name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - run: rustup update --no-self-update stable && rustup default stable

      - name: fmt
        run: cargo fmt --check

      - name: clippy
        run: cargo clippy --no-deps --all-targets --locked -- -D warnings

      - name: test
        run: cargo test --locked
